### ISSUE TITLE
feat: add fallback option in case of API error or downtime

### ISSUE THREAD

**Issue by Silthus** [datolabs-io/terraform-provider-backstage#160]
Hey @tdabasinskas 👋🏻
First of a big thank you for creating and maintaining this project ❤️.

At our company we are using it to automatically enrich all of our infrastructure with labels and directly tie each unit of deployment (stack) back to a component in Backstage.

However this comes with the risk of blocking infrastructure deployments if Backstage is down. To mitigate this I would like to propose the following non-breaking feature addition to the provider:

---

- **Feature**: add an input option to pass in a `fallback` object that must map to the output spec of the data resource.
- **Implementation**: If the `fallback` input is provided, catch **ANY** error, print a warning, and then return the fallback without bubbling up the error.
- **Consequences**: The provider can now be safely used inside deployment pipelines on the critical path without blocking deployments. Users can optionally provide a fallback, for example using remote state or a set of default return values, to mitigate the risk of the Backstage backend being down.
- **Bonus**: Add a circuit breaker and retry mechanisms to make it even more robust. For example when using the provider while also deploying an update to the Backstage database.

---

*P.s.: I might also present this **Component Stack** solution touched above in the BackstageCon 2025 in London. If you are interested to talk I sent you a network request on LinkedIn.*

**Comment by tdabasinskas** [comment]
Hi @Silthus,

Thanks for the feedback - I'm happy you find the provider useful.

The request makes sense, would love to improve the resilience of the provider. Let me see if I can find some time to implement this.

**Comment by Silthus** [comment]
If you are open for it, I could also take a stab at it and send a PR.

Which do you prefer?

**Comment by tdabasinskas** [comment]
If you're willing to send a PR for `fallback` functionality, I would really appreciate it!

I've already implemented retries (in addition to timeouts) in #163.

**Comment by Silthus** [comment]
What do you think, should this be implemented at the provider level or per data source, or both?

**Comment by tdabasinskas** [comment]
Even implementing this on each data source will result in some code duplication, I think that's the way to go. As each data source returns different types and in fact actually different data, I'm not sure how we could define the fallbacks at the provider level.

**Comment by Silthus** [comment]
Thank you for tackling this so quickly @tdabasinskas 🚀

Just an FYI: the latest provider version [does not have the changes](https://registry.terraform.io/providers/tdabasinskas/backstage/latest/docs/data-sources/entities) after the rename/move to the new Github Org and one needs to use the provider from the new org in the TF registry.

![image](https://github.com/user-attachments/assets/ef4f5860-16cf-46b7-8637-488db97106df)
 
This is the correct one to use: https://registry.terraform.io/providers/datolabs-io/backstage/latest/docs

I don't know if this was intentional, or is some kind of quirk from Terraform.

**Comment by tdabasinskas** [comment]
Hi @Silthus,

Yeah, a repository transfer is a bit messy 🙈 It's not possible to rename/transfer/delete provider in Terraform registry, so now there are two there: the one from `tdabasinskas` frozen in the last version before transfer, and one from `datolabs-io`, which gonna have all new versions.

The intention is that all current provider users will switch to https://registry.terraform.io/providers/datolabs-io/backstage/latest/docs. Unfortunately, since https://registry.terraform.io/providers/tdabasinskas/backstage/latest no longer has a corresponding GitHub repository, I cannot update the documentation to instruct users to switch.
